Use configuration file for openssl certificate configuration.

diff --git a/debian/dovecot-core.postinst b/debian/dovecot-core.postinst
--- a/debian/dovecot-core.postinst
+++ b/debian/dovecot-core.postinst
@@ -134,17 +134,18 @@ if [ "$1" = "configure" ]; then
       db_get dovecot-core/ssl-cert-name
       COMMONNAME="$RET"
       MAILNAME="$(cat /etc/mailname 2> /dev/null || echo "$COMMONNAME")"
-      (openssl req -newkey rsa:2048  -x509 -days 3652.5 -nodes \
-	  -rand /dev/urandom -out $SSL_CERT -keyout $SSL_KEY > /dev/null 2>&1 <<+
-.
-.
-.
-Dovecot mail server
-$COMMONNAME
-$COMMONNAME
-root@$MAILNAME
-+
-      ) || echo "Warning : Bad SSL config, can't generate certificate."
+      SSLCONF="$(mktemp)" || exit 1
+      TMPOUT="$(mktemp)" || exit 1
+
+      sed -e s#@commonName@#"$COMMONNAME"# \
+          -e s#@emailAddress@#"$root@MAILNAME"# \
+          /usr/share/dovecot/ssleay.cnf > $SSLCONF
+
+      if ! openssl req -config $SSLCONF -newkey rsa:2048  -x509 -days 3652.5 -nodes \
+      -out $SSL_CERT -keyout $SSL_KEY > $TMPOUT 2>&1; then
+          echo "Warning : Bad SSL config, can't generate certificate. Openssl output was: " >&2
+        cat $TMPOUT >&2
+      fi
 
       ucfr dovecot-core $SSL_CERT
       ucfr dovecot-core $SSL_KEY
