* debian/dovecot-common.postrm: do not break if /etc/ssl/certs does not   exist. (Closes: #524865) * debian/patches/dovecot-managesieve-dist: updated to 0.10.6.

diff --git a/debian/dovecot-common.postrm b/debian/dovecot-common.postrm
--- a/debian/dovecot-common.postrm
+++ b/debian/dovecot-common.postrm
@@ -23,18 +23,21 @@ if [ "$1" = "purge" ] ; then
 		fi
 	done
 
-        userdel dovecot || true;
-	cd /etc/ssl/certs
-	PATH=$PATH:/usr/bin/ssl
-	if [ -f dovecot.pem ]; then
-		echo "SSL certificate /etc/ssl/certs/dovecot.pem is NOT removed."
-		echo "Please remove manually if required."
-	fi
-	if [ -f ../private/dovecot.pem ]; then
-		echo "SSL certificate /etc/ssl/private/dovecot.pem is NOT removed."
-		echo "Please remove manually if required."
-	fi
-	if [ -d /var/run/dovecot ]; then rm -rf /var/run/dovecot; fi
+    userdel dovecot || true;
+
+    if [ -d /etc/ssl/certs ]; then
+	    cd /etc/ssl/certs
+        PATH=$PATH:/usr/bin/ssl
+        if [ -f dovecot.pem ]; then
+            echo "SSL certificate /etc/ssl/certs/dovecot.pem is NOT removed."
+            echo "Please remove manually if required."
+        fi
+        if [ -f ../private/dovecot.pem ]; then
+            echo "SSL certificate /etc/ssl/private/dovecot.pem is NOT removed."
+            echo "Please remove manually if required."
+        fi
+        if [ -d /var/run/dovecot ]; then rm -rf /var/run/dovecot; fi
+    fi
 fi
 
 #DEBHELPER#
